spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://ec2-52-19-96-181.eu-west-1.compute.amazonaws.com:5432/dbf2epmf336a4a"
    username: rgvwijxpohldnq
    password: faa3c3e6973d538d38c5fa4de0aa2efe38f69d98a46ddffddc3024d61a0ee8d7
